name: Build and Deploy to DEV
on:
    push:
        branches:
            -   development

jobs:
    build:
        name: Build and Deploy
        runs-on: ubuntu-latest
        steps:
            - name: Setup Enviroment
              uses: shivammathur/setup-php@v2
              with:
                php-version: '8.0'
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.3
              with:
                host: ${{ secrets.HOST }}
                username: ${{ secrets.USERNAME }}
                password: ${{ secrets.PASSWORD }}
                port: ${{ secrets.PORT }}
                script: "cd ${{ secrets.PATH }} && ./deploy-dev.sh"
         
